-- Tabela PRODUTO
CREATE TABLE PRODUTO (
	ID_PRODUTO INT PRIMARY KEY,
	NOME_PRODUTO VARCHAR(100) NOT NULL,
	CLASSIFICACAO INT NOT NULL,
	COD_BARRAS BIGINT,
	PESO NUMERIC(6,3)
    );

-- Tabela CLIENTE
CREATE TABLE CLIENTE (
	ID_CLIENTE INT PRIMARY KEY,
	NOME_CLIENTE VARCHAR(100) NOT NULL,
);

-- Tabela ENDERECO_CLIENTE
CREATE TABLE ENDERECO_CLIENTE (
	ID_ENDERECO SERIAL PRIMARY KEY,
	ID_CLIENTE INT NOT NULL,
	CIDADE VARCHAR(100) NOT NULL,
	BAIRRO VARCHAR(100) NOT NULL,
	NUMERO VARCHAR(6) NOT NULL,
	COORDENADAS VARCHAR(23),
	TIPO_LOGRADOURO VARCHAR(100),
	COMPLEMENTO VARCHAR(100),
	PONTO_REFERENCIA VARCHAR(100),
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- Tabela PEDIDO
CREATE TABLE PEDIDO(
	N_NOTA INT PRIMARY KEY,
	DT_NOTA DATE,
	ID_CLIENTE INT,
	ID_ENDERECO INT,
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
	FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO_CLIENTE(ID_ENDERECO)
);

-- Tabela PRODUTO_PEDIDO
CREATE TABLE PRODUTO_PEDIDO (
	PEDIDO_N_NOTA INT,
	PRODUTO_ID_PRODUTO INT,
	QUANT_PEDIDO NUMERIC(6,3),
	PRIMARY KEY (PEDIDO_N_NOTA, PRODUTO_ID_PRODUTO),
	FOREIGN KEY (PEDIDO_N_NOTA) REFERENCES PEDIDO(N_NOTA),
	FOREIGN KEY (PRODUTO_ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

-- Tabela VEICULO
CREATE TABLE VEICULO (
	PLACA INT PRIMARY KEY,
	MARCA VARCHAR(50) NOT NULL,
	MODELO VARCHAR(50),
	TIPO_CARGA INT NOT NULL,
	LIMITE_PESO NUMERIC(6,3)
);

-- Tabela ENTREGA
CREATE TABLE ENTREGA (
	ID_ENTREGA INT PRIMARY KEY,
	STATUS VARCHAR(30),
	PEDIDO_N_NOTA INT,
	VEICULO_PLACA INT,
	FOREIGN KEY (PEDIDO_N_NOTA) REFERENCES PEDIDO(N_NOTA),
	FOREIGN KEY (VEICULO_PLACA) REFERENCES VEICULO(PLACA)
);

-- Tabela ROTA
CREATE TABLE ROTA (
	ID_ROTA SERIAL PRIMARY KEY,
	SEQUENCIA_DESCARGA VARCHAR(1000),
	ENTREGA_ID_ENTREGA INT,
	FOREIGN KEY (ENTREGA_ID_ENTREGA) REFERENCES ENTREGA(ID_ENTREGA)
);

-- Tabela USUARIO
CREATE TABLE USUARIO (
	ID_USUARIO SERIAL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	SENHA VARCHAR(25) NOT NULL,
	CARGO VARCHAR(100),
);

-- Tabela USUARIO_ENTREGA
CREATE TABLE USUARIO_ENTREGA (
	ENTREGA_ID_ENTREGA INT,
	USUARIO_ID_USUARIO INT,
	PRIMARY KEY (ENTREGA_ID_ENTREGA, USUARIO_ID_USUARIO),
	FOREIGN KEY (ENTREGA_ID_ENTREGA) REFERENCES ENTREGA(ID_ENTREGA),
	FOREIGN KEY (USUARIO_ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);