-- Tabela PRODUTO
CREATE TABLE PRODUTO (
	ID_PRODUTO INT PRIMARY KEY NOT NULL,
	NOME_PRODUTO VARCHAR(100),
	CLASSIFICACAO INT,
	PESO NUMERIC(20,3)
);

-- Tabela CLIENTE
CREATE TABLE CLIENTE (
	ID_CLIENTE INT PRIMARY KEY NOT NULL,
	NOME_CLIENTE VARCHAR(100)
);

-- Tabela ENDERECO_CLIENTE
CREATE TABLE ENDERECO_CLIENTE (
	ID_ENDERECO SERIAL PRIMARY KEY NOT NULL,
	ID_CLIENTE INT NOT NULL,
	CIDADE VARCHAR(100),
	BAIRRO VARCHAR(100),
	NUMERO VARCHAR(6),
	COORDENADAS VARCHAR(150),
	ENDERECO VARCHAR(100),
	COMPLEMENTO VARCHAR(100),
	PONTO_REFERENCIA VARCHAR(100),
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- Tabela PEDIDO
CREATE TABLE PEDIDO(
	N_NOTA INT PRIMARY KEY NOT NULL,
	DT_NOTA DATE,
	ID_CLIENTE INT,
	ID_ENDERECO INT,
	DATA_IMPORTACAO TIMESTAMP,
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
	FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO_CLIENTE(ID_ENDERECO)
);

-- Tabela PRODUTO_PEDIDO
CREATE TABLE PRODUTO_PEDIDO (
	PEDIDO_N_NOTA INT,
	PRODUTO_ID_PRODUTO INT,
	QUANT_PEDIDO NUMERIC(20,3),
	PRIMARY KEY (PEDIDO_N_NOTA, PRODUTO_ID_PRODUTO),
	FOREIGN KEY (PEDIDO_N_NOTA) REFERENCES PEDIDO(N_NOTA),
	FOREIGN KEY (PRODUTO_ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

-- Tabela VEICULO
CREATE TABLE VEICULO (
	PLACA VARCHAR(7) PRIMARY KEY NOT NULL,
	MARCA VARCHAR(50),
	MODELO VARCHAR(50),
	TIPO_CARGA INT,
	LIMITE_PESO NUMERIC(20,3)
);

-- Tabela ENTREGA
CREATE TABLE ENTREGA (
	ID_ENTREGA INT PRIMARY KEY NOT NULL,
	STATUS VARCHAR(30),
	PEDIDO_N_NOTA INT,
	VEICULO_PLACA VARCHAR(7),
	DATA_ENTREGA DATE,
	FOREIGN KEY (PEDIDO_N_NOTA) REFERENCES PEDIDO(N_NOTA),
	FOREIGN KEY (VEICULO_PLACA) REFERENCES VEICULO(PLACA)
);

-- Tabela ROTA
CREATE TABLE ROTA (
	ID_ROTA SERIAL PRIMARY KEY NOT NULL,
	SEQUENCIA_DESCARGA VARCHAR(1000),
	ENTREGA_ID_ENTREGA INT,
	FOREIGN KEY (ENTREGA_ID_ENTREGA) REFERENCES ENTREGA(ID_ENTREGA)
);

-- Tabela USUARIO
CREATE TABLE USUARIO (
	ID_USUARIO SERIAL PRIMARY KEY NOT NULL,
	NOME VARCHAR(100),
	SENHA VARCHAR(25),
	CARGO VARCHAR(100)
);

-- Tabela USUARIO_ENTREGA
CREATE TABLE USUARIO_ENTREGA (
	ENTREGA_ID_ENTREGA INT,
	USUARIO_ID_USUARIO INT,
	PRIMARY KEY (ENTREGA_ID_ENTREGA, USUARIO_ID_USUARIO),
	FOREIGN KEY (ENTREGA_ID_ENTREGA) REFERENCES ENTREGA(ID_ENTREGA),
	FOREIGN KEY (USUARIO_ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE IF NOT EXISTS usuario_metricas (
    usuario_id      INTEGER PRIMARY KEY REFERENCES usuario(id_usuario),
    rotas_aceitas   INTEGER,
	rotas_recusadas INTEGER,
    atualizado_em   TIMESTAMP
);
